# Generated by Django 3.1.2 on 2020-10-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baguette',
            name='img_src',
            field=models.CharField(default='', max_length=400),
        ),
    ]
