# Generated by Django 3.1.2 on 2020-10-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_baguette_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baguette',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
